#!/usr/bin/env python
# encoding: utf-8
"""
app.py

Created by 刘 智勇 on 2013-06-02.
Copyright (c) 2013 __MyCompanyName__. All rights reserved.
"""

import sys
import os


def main():
	pass


if __name__ == '__main__':
	main()

