#! /usr/bin/env bash

BASE=$(dirname ${BASH_SOURCE[0]})

# handles synbolic link
if [ -h "$BASE" ]; then
    while [ -h "$BASE" ]; do
        BASE=$(readlink -m "$BASE")
    done
fi

# convert to absolute path
pushd . > /dev/null
cd "$(dirname ${BASE})" > /dev/null
BASE=$(pwd)
popd > /dev/null

# handles synbolic link
if [ -h "$BASE" ]; then
    while [ -h "$BASE" ]; do
        BASE=$(readlink -m "$BASE")
    done
fi

export BASE
export VIRTUALENV_BIN=$(which virtualenv-2.7)
export REQUIREMENTS="$BASE/tools/requirements.txt"
export REQUIREMENT_EXCLUDES="$BASE/tools/requirement_excludes.txt"
export STAGING_REQUIREMENTS="$BASE/tools/staging_requirements.txt"
export VIRTUALENV_PATH="$BASE/.py"
export PYTHON_PACKAGES="$BASE/tools/python-packages"
export LEIN_HOME="$BASE/algo/avalon/leiningen"

source $BASE/tools/functions.sh

case $1 in
    freeze)
        freeze
        ;;
    upgrade)
        upgrade
        ;;
    quit)
        quit
        ;;
    *)
        detect_environ
        $BASE/tools/root_install.sh
        if v_is_install; then
            upgrade
        else
            v_install
        fi
        # install staging packages
        if [[ $GUOKR_ENVIRON != "PRODUCTION" ]]; then
            python tools/update_mercurial.py
            staging_upgrade
        fi
        ;;
esac
